formatting

diff --git a/examples/backlight b/examples/backlight
--- a/examples/backlight
+++ b/examples/backlight
@@ -1,21 +1,76 @@
 #!/bin/sh
+SYS="/sys/class/backlight/`ls -1 /sys/class/backlight/ | head -1`"
+
+USAGE() {
+    backlight=`basename $0` || backlight=backlight
+    test -n "$1" && /bin/echo -e "\n###\n$@\n###"
+    cat>/dev/stderr<<EOF
+
+USAGE:
+    $backlight -get
+    $backlight { -set | -inc | -dec } percent
+    $backlight -install [ groupname ]
+
+'$backlight { -set | -inc | -dec }' requires
+/sys/class/backlight/*/brightness to be writeable for the effective
+user. Running $backlight as root (e.g. via sudo) will obviously do it,
+but better to make 'brightness' writeable for a group at boot time.
+
+'$backlight -install' will install, enable and run a systemd service
+making 'brightness' writeable by the specified group, or for the video
+group if none specified.
+
+'$backlight -install' will replace the
+/etc/systemd/system/backlightgroup.service it if it already exists.
+
+'$backlight -install' must be run as root, requires your system to use
+systemd and have systemctl in the \$PATH.
+
+EOF
+	exit 1
+}
+
+test -e "$SYS/brightness" -a -e "$SYS/max_brightness" || USAGE "# No supported backlight system in /sys/class/backlight"
+
+test "-install" = "$1" && {
+    test `id -u` -eq 0 || USAGE "# 'backlight -install' must be run as root"
+    test -d /etc/systemd/system || USAGE "# systemd must be in use to -install\n# ('/etc/systemd/system/' not found.)"
+    GRP=video
+    test -n "$2" && GRP=$2
+    grep -E "^$GRP:" /etc/group >/dev/null || USAGE "# group '$GRP' not found in /etc/group"
+    cat>/etc/systemd/system/backlightgroup.service<<EOF
+[Unit]
+Description=Permission for group $GRP to set backlight brightness
+After=syslog.target
+
+[Service]
+Type=oneshot
+ExecStart=/bin/sh -c '/bin/chgrp $GRP /sys/class/backlight/*/brightness ; /bin/chmod g+w /sys/class/backlight/*/brightness'
+RemainAfterExit=no
+
+[Install]
+WantedBy=sysinit.target
+EOF
+    systemctl enable backlightgroup.service || USAGE "# failed to enable the backlightgroup.service"
+    systemctl start backlightgroup.service || USAGE "# failed to start the backlightgroup.service"
+    systemctl status --no-pager backlightgroup.service
+    echo
+    ls -l /sys/class/backlight/*/brightness
+    exit 0
+}
 # Set LOWEST to 0 to be able to completely turn the backlight off
 # or to a higher value (e.g. 1) to prevent turning the light completely off
-# as this might be considered turning the screen of and "xset dpms force on"
+# as this might be considered turning the screen off and "xset dpms force on"
 # on some systems will turn up the light if it's set to 0
 LOWEST=1 
 
-test "`hostname`" = "fraxlap" && exec xbacklight "$@"
-
-SYS="/sys/class/backlight/`ls -1 /sys/class/backlight/ | head -1`"
-MAX=`cat $SYS/max_brightness`
-CUR=`cat $SYS/brightness`
+MAX=`cat "$SYS/max_brightness"`
+CUR=`cat "$SYS/brightness"`
 
 test "-get" = "$1" && {
     echo $(($CUR*100/$MAX))%
     exit 0
 }
-
 
 OP=$1
 VAL=`echo $2 | sed 's/[^0-9]*\([0-9][0-9]*\).*/\1/'` # just keep the first found consecutive digits
@@ -34,13 +89,7 @@ case "$OP" in
 	NVAL=$(($CUR-$VAL*$MAX/100))
 	;;
     *)
-	backlight=`basename $0` || backlight=backlight
-	cat<<EOF
-USAGE:
-    $backlight -get
-    $backlight { -set | -inc | -dec } percent
-EOF
-	exit 1
+	USAGE
 	;;
 esac
 test $NVAL -gt $MAX && NVAL=$MAX
