typo bugfix

diff --git a/examples/fraxlock b/examples/fraxlock
--- a/examples/fraxlock
+++ b/examples/fraxlock
@@ -2,10 +2,10 @@
 if [ "`tty | cut -c-8`" = "/dev/tty" ]; then
     # we are on "real" console even though X might be running and DISPLAY is set
     if which physlock >/dev/null; then 
-	physlock -sm || { C=$?; echo 'fraxlock ERROR! "physlock -sm" failed!' >/dev/stderr; exit $? ;}
+	physlock -sm || { C=$?; echo 'fraxlock ERROR! "physlock -sm" failed!' >/dev/stderr; exit $C ;}
 	exit 0
     elif which vlock >/dev/null; then
-	vlock -a || { C=$?; echo 'fraxlock ERROR! "vlock -a" failed!' >/dev/stderr; exit $? ;}
+	vlock -a || { C=$?; echo 'fraxlock ERROR! "vlock -a" failed!' >/dev/stderr; exit $C ;}
 	echo 'fraxlock WARNING! For full functionality: [ apt install physlock ]' >/dev/stderr
 	exit 0
     else
@@ -72,7 +72,7 @@ elif [ -n "$DISPLAY" ]; then
 else
     # on non-console terminal without X DISPLAY... just trying to lock the terminal
     which vlock >/dev/null || { echo 'fraxlock ERROR! No executable vlock! [ apt install vlock ]' >/dev/stderr; exit 1;}
-    vlock || { C=$?; echo 'fraxlock ERROR! "vlock" failed!' >/dev/stderr; exit $? ;}
+    vlock || { C=$?; echo 'fraxlock ERROR! "vlock" failed!' >/dev/stderr; exit $C ;}
     exit 0
 fi
 echo 'WARNING: You are beyond the point of no return!' >/dev/stderr
